#!/bin/bash

cat << EOF > setting.sql
CREATE USER IF NOT EXISTS  $WORDPRESS_DB_USER@$WORDPRESS_HOST IDENTIFIED BY '$WORDPRESS_DB_PASSWORD';
CREATE DATABASE IF NOT EXISTS $WORDPRESS_DB_NAME;
GRANT ALL privileges ON $WORDPRESS_DB_NAME.* TO $WORDPRESS_DB_USER@$WORDPRESS_HOST;
EOF

mysqld -u root -p$MYSQL_ROOT_PASSWORD < setting.sql
rm setting.sql
